from django.conf.urls import url, patterns
from reportes.views import *
from ruedalaSessions.views import *

urlpatterns = patterns(
    '',
    url(
        r'^inicio/$',
        InicioView.as_view(),
        name='inicio'),
    url(
        r'^prestamos/$',
        PrestamosView.as_view(),
        name='prestamos'),
    url(
        r'^agregar-prestamo/$',
        AgregarPrestamoView.as_view(),
        name='agregar-prestamo'),
    url(
        r'^ver-prestamos/$',
        VerPrestamosView.as_view(),
        name='ver_prestamos'),
    url(
        r'^prestamos-usuario/(?P<id>\d+)/$',
        PrestamosUsuarioView.as_view(),
        name='prestamos_usuario'),
    url(
        r'^detalle-prestamo/(?P<id>\d+)/$',
        DetallePrestamoView.as_view(),
        name='detalle_prestamo'),
    url(
        r'^editar-prestamo/(?P<id>\d+)/$',
        'reportes.views.editar_prestamo',
        name='editar_prestamo'),
    url(
        r'^biciescuela/$',
        BiciescuelaView.as_view(),
        name='biciescuela'),
    url(
        r'^agregar-biciescuela/$',
        AgregarBiciescuelaView.as_view(),
        name='agregar-biciescuela'),
    url(
        r'^ver-biciescuelas/$',
        VerBiciescuelasView.as_view(),
        name='ver_biciescuelas'),
    url(
        r'^biciescuelas-usuario/(?P<id>\d+)/$',
        BiciescuelasUsuarioView.as_view(),
        name='biciescuelas_usuario'),
    url(
        r'^detalle-biciescuela/(?P<id>\d+)/$',
        DetalleBiciescuelaView.as_view(),
        name='detalle_biciescuela'),
    url(
        r'^editar-biciescuela/(?P<id>\d+)/$',
        'reportes.views.editar_biciescuela',
        name='editar_biciescuela'),
    url(
        r'^ver-usuarios/$',
        VerUsuariosView.as_view(),
        name='ver_usuarios'),
    url(
        r'^registro-exitoso/$',
        RegistroExitoso.as_view(),
        name='registro_exitoso'),
    url(
        r'^carnetizacion/$',
        Carnetizacion.as_view(),
        name='carnetizacion'),
    url(
        r'^ver-carnets/(?P<id>\d+)/$',
        VerCarnets.as_view(),
        name='ver_carnets'),
    url(
        r'^cambiar-foto-carnet/(?P<id>\d+)/$',
        'reportes.views.cambiar_carnet_foto',
        name='cambiar_carnet_foto'),
    url(
        r'^actualizar-status-carnet/(?P<id>\d+)/$',
        'reportes.views.actualizar_status_carnet',
        name='actualizar_status_carnet'),
    url(
        r'^agregar-fecha-entrega/(?P<id>\d+)/$',
        'reportes.views.agregar_fecha_entrega',
        name='agregar_fecha_entrega'),
    url(
        r'^registro-bicicletas/$',
        RegistroBicicletasView.as_view(),
        name='registro_bicicletas'),
    url(
        r'^agregar-bicicleta/$',
        AgregarBicicletaView.as_view(),
        name='agregar_bicicleta'),
    url(
        r'^ver-bicicletas/$',
        VerBicicletasView.as_view(),
        name='ver_bicicletas'),
    url(
        r'^crear-historial/(?P<id>\d+)/$',
        CrearHistorialView.as_view(),
        name='crear_historial'),
    url(
        r'^historial-bicicleta/(?P<id>\d+)/$',
        HistorialBicicletaView.as_view(),
        name='historial_bicicleta'),
    url(
        r'^cargar-historial$',
        CargarHistorialView.as_view(),
        name='cargar_historial'),
    url(
        r'^editar-historial/(?P<id>\d+)/$',
        EditarHistorialView.as_view(),
        name='editar_historial'),
    url(
        r'^editar-historial-f/(?P<id>\d+)/$',
        'reportes.views.editar_historial',
        name='editar_historial_f'),
    url(
        r'^eliminar_bicicleta/(?P<id>\d+)/$',
        'reportes.views.eliminar_bicicleta',
        name='eliminar_bicicleta'),
    url(
        r'^descargar-biciescuelas/$',
        'reportes.views.descargar_biciescuelas',
        name='descargar-biciescuelas'),
    url(
        r'^descargar-prestamos/$',
        'reportes.views.descargar_prestamos',
        name='descargar-prestamos'),
    url(
        r'^descargar-carnets-listos/$',
        'reportes.views.descargar_carnets_listos',
        name='descargar-carnets-listos'),
    url(
        r'^descargar-carnets-entregados/$',
        'reportes.views.descargar_carnets_entregados',
        name='descargar-carnets-entregados'),
    url(
        r'^descargar-bicicletas/$',
        'reportes.views.descargar_bicicletas',
        name='descargar-bicicletas'),
    url(
        r'^descargar-historial/(?P<id>\d+)/$',
        'reportes.views.descargar_historial',
        name='descargar-historial'),
    url(
        r'^descargar-historial-general/$',
        'reportes.views.descargar_historial_general',
        name='descargar-historial-general'),
)
